2020/09/04 08:14:15 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/pps.conf:21
2020/09/04 08:17:43 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/pps.conf:21
2020/09/04 08:18:40 [error] 19#19: *1 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.24.0.1, server: frontend.pps.loc, request: "GET / HTTP/1.1", host: "127.0.0.1"
2020/09/04 08:18:40 [error] 19#19: *1 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.24.0.1, server: frontend.pps.loc, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2020/09/04 08:18:42 [error] 19#19: *1 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.24.0.1, server: frontend.pps.loc, request: "GET / HTTP/1.1", host: "127.0.0.1"
2020/09/04 08:18:42 [error] 19#19: *1 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.24.0.1, server: frontend.pps.loc, request: "GET / HTTP/1.1", host: "127.0.0.1"
2020/09/04 08:29:08 [error] 19#19: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidConfigException: The directory is not writable by the Web process: /usr/share/nginx/html/frontend/web/assets in /usr/share/nginx/html/vendor/yiisoft/yii2/web/AssetManager.php:215
Stack trace:
#0 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Object.php(107): yii\web\AssetManager->init()
#1 [internal function]: yii\base\Object->__construct(Array)
#2 /usr/share/nginx/html/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#3 /usr/share/nginx/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\web\\AssetMa...', Array, Array)
#4 /usr/share/nginx/html/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\web\\AssetMa...', Array, Array)
#5 /usr/share/nginx/html/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#6 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Application.php(605): yii\di\ServiceLocator->get('assetManager')
#7 /usr/share" while reading upstream, client: 172.24.0.1, server: frontend.pps.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "frontend.pps.loc"
2020/09/04 08:29:08 [error] 19#19: *1 FastCGI sent in stderr: "PHP message: An Error occurred while handling another error:
yii\base\InvalidConfigException: The directory is not writable by the Web process: /usr/share/nginx/html/frontend/web/assets in /usr/share/nginx/html/vendor/yiisoft/yii2/web/AssetManager.php:215
Stack trace:
#0 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Object.php(107): yii\web\AssetManager->init()
#1 [internal function]: yii\base\Object->__construct(Array)
#2 /usr/share/nginx/html/vendor/yiisoft/yii2/di/Container.php(381): ReflectionClass->newInstanceArgs(Array)
#3 /usr/share/nginx/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\web\\AssetMa...', Array, Array)
#4 /usr/share/nginx/html/vendor/yiisoft/yii2/BaseYii.php(348): yii\di\Container->get('yii\\web\\AssetMa...', Array, Array)
#5 /usr/share/nginx/html/vendor/yiisoft/yii2/di/ServiceLocator.php(135): yii\BaseYii::createObject(Array)
#6 /usr/share/nginx/html/vendor/yiisoft/yii2/base/Application.php(605): yii\di\ServiceLocator->get('assetManager')
#7 /usr/share" while reading upstream, client: 172.24.0.1, server: frontend.pps.loc, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.24.0.2:9000", host: "frontend.pps.loc", referrer: "http://frontend.pps.loc/"
2020/09/07 07:58:16 [error] 19#19: *4 open() "/usr/share/nginx/html/frontend/web404" failed (2: No such file or directory), client: 172.24.0.1, server: frontend.pps.loc, request: "GET /_intellij_phpdebug_validator.php HTTP/1.1", host: "127.0.0.1"
2020/11/04 06:48:06 [error] 19#19: *1 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.25.0.1, server: backend.pps.loc, request: "GET /test.php HTTP/1.1", host: "backend.pps.loc"
2020/11/04 06:59:45 [error] 19#19: *76 open() "/usr/share/nginx/html/backend/web404" failed (2: No such file or directory), client: 172.25.0.1, server: backend.pps.loc, request: "GET /test.php HTTP/1.1", host: "backend.pps.loc"
2020/11/18 11:52:40 [error] 19#19: *204 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /transaction/update-status?id=0753f2f48e756a0cffd664177eb53e7b HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/transaction/withdraw"
2020/11/18 15:32:39 [alert] 1#1: worker process 19 exited on signal 9
2020/11/19 09:26:01 [error] 19#19: *137 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.26.0.1, server: backend.pps.loc, request: "POST /user-payment-system/individual-settings?id=366 HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=366"
2020/11/20 12:35:55 [warn] 19#19: *322 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /site/log?folder=backend&file=2020-11-20 HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/site/log?folder=backend"
2020/11/26 15:00:30 [alert] 1#1: worker process 19 exited on signal 9
2020/12/01 09:06:41 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/01 09:06:42 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/01 09:06:47 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/01 09:06:47 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/01 09:06:48 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/01 09:06:50 [error] 19#19: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: backend.pps.loc, request: "GET /user-payment-system/index HTTP/1.1", upstream: "fastcgi://172.26.0.7:9000", host: "backend.pps.loc", referrer: "http://backend.pps.loc/user-payment-system/configure?id=367"
2020/12/07 14:58:13 [error] 19#19: *1 open() "/usr/share/nginx/html/frontend/web404" failed (2: No such file or directory), client: 172.18.0.1, server: app.loc, request: "GET / HTTP/1.1", host: "localhost:81"
2020/12/07 14:58:13 [error] 19#19: *1 open() "/usr/share/nginx/html/frontend/web404" failed (2: No such file or directory), client: 172.18.0.1, server: app.loc, request: "GET /favicon.ico HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/"
2020/12/07 15:00:07 [error] 19#19: *1 open() "/usr/share/nginx/html/frontend/web404" failed (2: No such file or directory), client: 172.18.0.1, server: app.loc, request: "GET / HTTP/1.1", host: "localhost:81"
2020/12/07 15:00:31 [error] 19#19: *1 open() "/usr/share/nginx/html/frontend/web404" failed (2: No such file or directory), client: 172.18.0.1, server: app.loc, request: "GET / HTTP/1.1", host: "localhost:81"
2020/12/07 15:28:36 [warn] 1#1: server name "app.loc/" has suspicious symbols in /etc/nginx/conf.d/app.conf:3
2020/12/08 11:57:08 [error] 19#19: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.19.0.1, server: app.loc, request: "GET / HTTP/1.1", host: "localhost:81"
2020/12/08 11:57:08 [error] 19#19: *1 open() "/usr/share/nginx/html404" failed (2: No such file or directory), client: 172.19.0.1, server: app.loc, request: "GET /favicon.ico HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/"
2020/12/08 11:58:00 [error] 19#19: *1 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.19.0.1, server: app.loc, request: "GET / HTTP/1.1", host: "localhost:81"
